### ISSUE TITLE
Subscriptions with `where` filter don't work

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/prisma-binding#139] opened 2018-04-18 11:46 UTC
Here's the link to a repository that describes how to reproduce the issue in the README: https://github.com/nikolasburk/subscriptions-issue

**Comment by marktani** [comment] 2018-04-18 12:42
I can reproduce the issue.

**Comment by ar1a** [comment] 2018-04-23 08:18
I have this also

**Comment by schickling** [comment] 2018-05-01 11:44
This should be fixed with Prisma 1.7.

**Closed by schickling** 2018-05-01 11:44 UTC
Labels: bug

**Comment by heymartinadams** [comment] 2018-05-03 11:54
Slightly unrelated since this applies to Prisma Cloud, but posting a link here for additional visibility (took me two days to find this crucial piece of information):

Upgrading the Prisma Cloud server (over at `https://app.prisma.sh/__WORKSPACE_SLUG__/clusters`) to v1.7 will resolve this issue.
https://github.com/graphcool/prisma/issues/2277#issuecomment-384557788
